### ISSUE TITLE
"display_container is not defined" error

### ISSUE THREAD

**Issue by garyee** [pycaret/pycaret#1100]
Hi,

I am using pycaret on Google Colab. Here is the code:
```
my_file = Path(pycaretPath+'/myvars.pkl')
if my_file.is_file():
  load_config(pycaretPath+'/myvars.pkl')
else:
  setup(X_train, target = 'class', test_data=X_test) 
  save_config(pycaretPath+'/myvars.pkl')

# compare all baseline models and select top 5
top5 = compare_models(n_select = 5) 
# tune top 5 base models
tuned_top5 = [tune_model(i) for i in top5]
# ensemble top 5 tuned models
bagged_top5 = [ensemble_model(i) for i in tuned_top5]
# blend top 5 base models 
blender = blend_models(estimator_list = top5) 
# select best model 
best = automl(optimize = 'AUC')
````

the code itself is the automl example code. I only added the save_config and load_config.
I think that the problem is connected to the load_config somehow.

**Comment by garyee** [comment]
Error was thrown [here](https://github.com/pycaret/pycaret/blob/63682f3e0629f5226b888d1bd0d7e025137c40d1/pycaret/internal/tabular.py#L2346)

**Comment by the-whopper** [comment]
I am also getting this error in a using save_config, load_config and compare_models in an ide setting

**Comment by Yard1** [comment]
I'll take a look

**Comment by Yard1** [comment]
Should be fixed in commit 68b2139a97184af1b51c50084721d13fd90d7f56 .

**Comment by the-whopper** [comment]
Hey @Yard1, still getting errors:
<img width="809" alt="load error1PNG" src="https://user-images.githubusercontent.com/79564693/110262910-33612e80-8009-11eb-930a-c53cac5a7ca5.PNG">

<img width="807" alt="load error2" src="https://user-images.githubusercontent.com/79564693/110262917-3825e280-8009-11eb-9fb8-53c519b1d1f8.PNG">

**Comment by the-whopper** [comment]
@Yard1 - Thank you, when updated to nightly building load_config is working. cheers
