### ISSUE TITLE
What are the correct steps to resume work on an experiment?

### ISSUE THREAD

**Issue by mkbldn** [pycaret/pycaret#1139]
I'm attempting to pick back up work on a experiment and I'm getting some funny behavior after loading my configuration and tuned model. Am I doing something wrong or is there an issue? I can't seem to find an example of the steps to resume. Any help would be greatly appreciated!

Forgot to mention that I'm working on a local installation of Jupyter Lab.

![image](https://user-images.githubusercontent.com/8095617/113314672-8c577600-92da-11eb-9342-5ff7bd780733.png)

```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-6-e17eae3e35cf> in <module>
----> 1 pred_holdout = predict_model(tuned_lgbm)

~\Anaconda3\envs\pycaret\lib\site-packages\pycaret\classification.py in predict_model(estimator, data, probability_threshold, encoded_labels, raw_score, round, verbose)
   1921         round=round,
   1922         verbose=verbose,
-> 1923         ml_usecase=MLUsecase.CLASSIFICATION,
   1924     )
   1925 

~\Anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py in predict_model(estimator, data, probability_threshold, encoded_labels, raw_score, round, verbose, ml_usecase, display)
   8461     # store predictions on hold-out in display_container
   8462     if df_score is not None:
-> 8463         display_container.append(df_score)
   8464 
   8465     gc.collect()

NameError: name 'display_container' is not defined
```

**Comment by Yard1** [comment]
This is an issue that has been fixed in development. Please install PyCaret nightly:
```
pip uninstall pycaret
pip install -U pycaret-nightly
```

**Comment by mkbldn** [comment]
That cleared up the predict model() error, but unfortunately I'm still getting strange looking output and errors from plot_model. For example after loading the environment then model I'm getting this output below from `plot_model(tuned_lgbm, plot='confusion_matrix')` (my target is is named 'target').


```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~\Anaconda3\envs\pycaret\lib\site-packages\pandas\core\indexes\base.py in get_loc(self, key, method, tolerance)
   3079             try:
-> 3080                 return self._engine.get_loc(casted_key)
   3081             except KeyError as err:

pandas\_libs\index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas\_libs\index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas\_libs\hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas\_libs\hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'target'

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
<ipython-input-6-8fffe2069bd6> in <module>
----> 1 plot_model(tuned_lgbm, plot = 'confusion_matrix')

~\Anaconda3\envs\pycaret\lib\site-packages\pycaret\classification.py in plot_model(estimator, plot, scale, save, fold, fit_kwargs, groups, use_train_data, verbose, display_format)
   1547         use_train_data=use_train_data,
   1548         system=True,
-> 1549         display_format=display_format,
   1550     )
   1551 

~\Anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py in plot_model(estimator, plot, scale, save, fold, fit_kwargs, groups, feature_name, label, use_train_data, verbose, system, display, display_format, is_in_evaluate)
   7210 
   7211         # execute the plot method
-> 7212         ret = locals()[plot]()
   7213         if ret:
   7214             plot_filename = ret

~\Anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py in confusion_matrix()
   6534                 groups=groups,
   6535                 display=display,
-> 6536                 display_format=display_format,
   6537             )
   6538 

~\Anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\plots\yellowbrick.py in show_yellowbrick_plot(visualizer, X_train, y_train, X_test, y_test, name, handle_train, handle_test, scale, save, fit_kwargs, groups, display, display_format, **kwargs)
     86     elif handle_train == "fit":
     87         logger.info("Fitting Model")
---> 88         visualizer.fit(X_train, y_train, **fit_kwargs_and_kwargs)
     89     elif handle_train == "fit_transform":
     90         logger.info("Fitting & Transforming Model")

~\Anaconda3\envs\pycaret\lib\site-packages\yellowbrick\classifier\base.py in fit(self, X, y, **kwargs)
    174         """
    175         # Super fits the wrapped estimator
--> 176         super(ClassificationScoreVisualizer, self).fit(X, y, **kwargs)
    177 
    178         # Extract the classes and the class counts from the target

~\Anaconda3\envs\pycaret\lib\site-packages\yellowbrick\base.py in fit(self, X, y, **kwargs)
    388         """
    389         if not check_fitted(self.estimator, is_fitted_by=self.is_fitted):
--> 390             self.estimator.fit(X, y, **kwargs)
    391         return self
    392 

~\Anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\pipeline.py in fit(self, X, y, **fit_kwargs)
    116 
    117     def fit(self, X, y=None, **fit_kwargs):
--> 118         result = super().fit(X, y=y, **fit_kwargs)
    119 
    120         self._carry_over_final_estimator_fit_vars()

~\Anaconda3\envs\pycaret\lib\site-packages\imblearn\pipeline.py in fit(self, X, y, **fit_params)
    279                                  self._log_message(len(self.steps) - 1)):
    280             if self._final_estimator != "passthrough":
--> 281                 self._final_estimator.fit(Xt, yt, **fit_params)
    282         return self
    283 

~\Anaconda3\envs\pycaret\lib\site-packages\sklearn\pipeline.py in fit(self, X, y, **fit_params)
    328         """
    329         fit_params_steps = self._check_fit_params(**fit_params)
--> 330         Xt = self._fit(X, y, **fit_params_steps)
    331         with _print_elapsed_time('Pipeline',
    332                                  self._log_message(len(self.steps) - 1)):

~\Anaconda3\envs\pycaret\lib\site-packages\sklearn\pipeline.py in _fit(self, X, y, **fit_params_steps)
    294                 message_clsname='Pipeline',
    295                 message=self._log_message(step_idx),
--> 296                 **fit_params_steps[name])
    297             # Replace the transformer of the step with the fitted
    298             # transformer. This is necessary when loading the transformer

~\Anaconda3\envs\pycaret\lib\site-packages\joblib\memory.py in __call__(self, *args, **kwargs)
    350 
    351     def __call__(self, *args, **kwargs):
--> 352         return self.func(*args, **kwargs)
    353 
    354     def call_and_shelve(self, *args, **kwargs):

~\Anaconda3\envs\pycaret\lib\site-packages\sklearn\pipeline.py in _fit_transform_one(transformer, X, y, weight, message_clsname, message, **fit_params)
    738     with _print_elapsed_time(message_clsname, message):
    739         if hasattr(transformer, 'fit_transform'):
--> 740             res = transformer.fit_transform(X, y, **fit_params)
    741         else:
    742             res = transformer.fit(X, y, **fit_params).transform(X)

~\Anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\preprocess.py in fit_transform(self, dataset, y)
    424         # for ml use ase
    425         if (self.ml_usecase == "classification") & (
--> 426             data[self.target].dtype == "object"
    427         ):
    428             self.le = LabelEncoder()

~\Anaconda3\envs\pycaret\lib\site-packages\pandas\core\frame.py in __getitem__(self, key)
   3022             if self.columns.nlevels > 1:
   3023                 return self._getitem_multilevel(key)
-> 3024             indexer = self.columns.get_loc(key)
   3025             if is_integer(indexer):
   3026                 indexer = [indexer]

~\Anaconda3\envs\pycaret\lib\site-packages\pandas\core\indexes\base.py in get_loc(self, key, method, tolerance)
   3080                 return self._engine.get_loc(casted_key)
   3081             except KeyError as err:
-> 3082                 raise KeyError(key) from err
   3083 
   3084         if tolerance is not None:

KeyError: 'target'
```

**Comment by Yard1** [comment]
Is it possible for you to create a reproductible notebook on google colab and share it here? Thanks.

**Comment by mkbldn** [comment]
Here's a [google collab](https://colab.research.google.com/drive/1U09DjEJsbAEyfmbKnG1lJKOOWlpvI2zG?usp=sharing) with the errors.

**Comment by Yard1** [comment]
Thanks. I've identified the issue. The problem is that when you save and load the model, by default, the entire pipeline is saved, while `plot_model` expects only the model itself. This will be accounted for in a future update but for now you can just do:

```
tuned_lgbm = load_model('lgbm_model_tuned').steps[-1][1] # get just the estimator from saved pipeline
```

**Comment by mkbldn** [comment]
> Thanks. I've identified the issue. The problem is that when you save and load the model, by default, the entire pipeline is saved, while `plot_model` expects only the model itself. This will be accounted for in a future update but for now you can just do:
> 
> ```
> tuned_lgbm = load_model('lgbm_model_tuned').steps[-1][1] # get just the estimator from saved pipeline
> ```

Thank you!
