### ISSUE TITLE
MemoryError: Unable to allocate 116. GiB for an array with shape (15554265202,) and data type int64

### ISSUE THREAD

**Issue by soerendip** [pycaret/pycaret#166]
I am using a table with 1092 rows and 127 features plus one categorical target column and I am getting this error above. Any idea what could be going wrong here? The table contains integer values and the target column has a total of two classes. 

     from pycaret.classification import * 
     clf1 = setup(data = data, 
             target = 'ORG',
             silent = False)
    > MemoryError: Unable to allocate 116. GiB for an array with shape (15554265202,) and data type int64

I think, the data is not that big. Am I doing something wrong?

**Comment by RahulSinghYYC** [comment]
i have the same issue as well and I even tried using pycaret 1.0.1 dev branch 

```
---------------------------------------------------------------------------
MemoryError                               Traceback (most recent call last)
<ipython-input-13-01657439561c> in <module>
----> 1 ano1=setup(data,normalize= True,ignore_features=['User'])

C:\Anaconda\envs\myenv\lib\site-packages\pycaret\anomaly.py in setup(data, categorical_features, categorical_imputation, ordinal_features, high_cardinality_features, numeric_features, numeric_imputation, date_features, ignore_features, normalize, normalize_method, transformation, transformation_method, handle_unknown_categorical, unknown_categorical_method, pca, pca_method, pca_components, ignore_low_variance, combine_rare_levels, rare_level_threshold, bin_numeric_features, remove_multicollinearity, multicollinearity_threshold, group_features, group_names, supervised, supervised_target, session_id, profile, verbose)
    708                                        features_to_group_ListofList = group_features_pass, #new
    709                                        group_name = group_names_pass, #new
--> 710                                        random_state = seed)
    711 
    712     progress.value += 1

C:\Anaconda\envs\myenv\lib\site-packages\pycaret\preprocess.py in Preprocess_Path_Two(train_data, ml_usecase, test_data, categorical_features, numerical_features, time_features, features_todrop, display_types, imputation_type, numeric_imputation_strategy, categorical_imputation_strategy, apply_zero_nearZero_variance, club_rare_levels, rara_level_threshold_percentage, apply_untrained_levels_treatment, untrained_levels_treatment_method, apply_cardinality_reduction, cardinal_method, cardinal_features, apply_ordinal_encoding, ordinal_columns_and_categories, apply_binning, features_to_binn, apply_grouping, group_name, features_to_group_ListofList, scale_data, scaling_method, Power_transform_data, Power_transform_method, remove_outliers, outlier_contamination_percentage, outlier_methods, remove_multicollinearity, maximum_correlation_between_features, remove_perfect_collinearity, apply_pca, pca_method, pca_variance_retained_or_number_of_components, random_state)
   2788     return(train_t.drop(target_variable,axis=1),test_t)
   2789   else:
-> 2790     train_t = pipe.fit_transform(train_data)
   2791     return(train_t.drop(target_variable,axis=1))

C:\Anaconda\envs\myenv\lib\site-packages\sklearn\pipeline.py in fit_transform(self, X, y, **fit_params)
    381         """
    382         last_step = self._final_estimator
--> 383         Xt, fit_params = self._fit(X, y, **fit_params)
    384         with _print_elapsed_time('Pipeline',
    385                                  self._log_message(len(self.steps) - 1)):

C:\Anaconda\envs\myenv\lib\site-packages\sklearn\pipeline.py in _fit(self, X, y, **fit_params)
    311                 message_clsname='Pipeline',
    312                 message=self._log_message(step_idx),
--> 313                 **fit_params_steps[name])
    314             # Replace the transformer of the step with the fitted
    315             # transformer. This is necessary when loading the transformer

C:\Anaconda\envs\myenv\lib\site-packages\joblib\memory.py in __call__(self, *args, **kwargs)
    350 
    351     def __call__(self, *args, **kwargs):
--> 352         return self.func(*args, **kwargs)
    353 
    354     def call_and_shelve(self, *args, **kwargs):

C:\Anaconda\envs\myenv\lib\site-packages\sklearn\pipeline.py in _fit_transform_one(transformer, X, y, weight, message_clsname, message, **fit_params)
    724     with _print_elapsed_time(message_clsname, message):
    725         if hasattr(transformer, 'fit_transform'):
--> 726             res = transformer.fit_transform(X, y, **fit_params)
    727         else:
    728             res = transformer.fit(X, y, **fit_params).transform(X)

C:\Anaconda\envs\myenv\lib\site-packages\pycaret\preprocess.py in fit_transform(self, dataset, y)
   1174       self.fit(data)
   1175       # fit without target and only categorical columns
-> 1176       array = self.ohe.transform(data.drop(self.target,axis=1,errors='ignore').select_dtypes(include=('object'))).toarray()
   1177       data_dummies = pd.DataFrame(array,columns= self.data_columns)
   1178       data_dummies.index = self.data_nonc.index

C:\Anaconda\envs\myenv\lib\site-packages\scipy\sparse\compressed.py in toarray(self, order, out)
   1023         if out is None and order is None:
   1024             order = self._swap('cf')[0]
-> 1025         out = self._process_toarray_args(order, out)
   1026         if not (out.flags.c_contiguous or out.flags.f_contiguous):
   1027             raise ValueError('Output array must be C or F contiguous')

C:\Anaconda\envs\myenv\lib\site-packages\scipy\sparse\base.py in _process_toarray_args(self, order, out)
   1187             return out
   1188         else:
-> 1189             return np.zeros(self.shape, dtype=self.dtype, order=order)
   1190 
   1191 

MemoryError: Unable to allocate 519. GiB for an array with shape (838860, 82983) and data type float64
```
Any help would be great thanks

**Comment by Janglee123** [comment]
I am facing the same issue. My data frame shape is (1280,4041). Yet my google colab crashes due to larger memory allocations.

**Comment by pycaret** [comment]
@Janglee123 @RahulSinghYYC @soerendip can anyone of you share the dataset so I can try to reproduce the issue and debug.

It is very likely this is a known bug and has already been fixed in dev-1.0.1 branch.

**Comment by RahulSinghYYC** [comment]
> @Janglee123 @RahulSinghYYC @soerendip can anyone of you share the dataset so I can try to reproduce the issue and debug.
> 
> It is very likely this is a known bug and has already been fixed in dev-1.0.1 branch.

@pycaret I have tried this using dev-1.0.1 branch as well but it's still not working

**Comment by RahulSinghYYC** [comment]
@pycaret I suppose can share the dataset but I cannot share it publicly. if I have a secure and private place to put the file then I can share it.

**Comment by soerendip** [comment]
Maybe a high cardinality feature got interpreted as categorical e.g. due to wrong data type??

________________________________

**Comment by pycaret** [comment]
@RahulSinghYYC Thanks. Can you please upload the file on google drive or drop box and share the link?

**Comment by RahulSinghYYC** [comment]
Hi 
Here is a sample example, the original file has a million lines similar to this sample set 

AccountID | Detail | Date | Debit | Credit | Memo | Flag
-- | -- | -- | -- | -- | -- | --
2432342 | Repairs | 2015-04-16 | 2348.65 | 0.00 | Parking | AXP
6575577 | Repairs | 2015-04-17 | 0.00 | -1343.74 | Parking | AXP
6576576 | Maintenance | 2015-04-18 | 0.00 | -3855.15 | Parking | AXP
4950000 | Maintenance | 2015-04-19 | 0.00 | -1299.87 | Parking | AXP

Please let me know

**Comment by GLevV** [comment]
Downcasting to float32 instead of default float64, and int16/int32 instead of default int64 could reduce memory usage. Also, using 'category' pandas type instead of object will give gain in memory and speed.

**Comment by pycaret** [comment]
@RahulSinghYYC Looking at the dataset I can guess this is caused by cardinality for 'AccountID'. Can you pass **AccountID** into **ignore_features** parameter of the setup function.

Let me know if that works.

**Comment by pycaret** [comment]
@RahulSinghYYC Is this issue resolved?

**Comment by AarthiKalyanasundaram** [comment]
Hi,
Is this issue got fixed?
![image](https://user-images.githubusercontent.com/36664362/90490926-dbda9e80-e15c-11ea-82f2-09df34fade75.png)
Still, i have this memory error. My dataset is not that big. Can anyone please let me know how to overcome this?

**Comment by AarthiKalyanasundaram** [comment]
But those data are confidential @pycaret

**Comment by Crisfon6** [comment]
i have the same problem creating a dataframe

**Comment by pycaret** [comment]
@Crisfon6 Can you share details about the dataset?

**Comment by Crisfon6** [comment]
@pycaret  i am sorry, the db are confidential

**Comment by pycaret** [comment]
@soerendip @Crisfon6 @GLevV 

This issue has been fixed in `pycaret==2.2`.

Please feel free to open another ticket if the issue persists.

Thanks

**Comment by AarthiKalyanasundaram** [comment]
Sure.

Thanks

**Comment by CHERKAOUISOUFIANE** [comment]
Scale your data, in case you didn't do that

**Comment by onkarS23** [comment]
**MemoryError: Unable to allocate 231. GiB for an array with shape (176066, 176066) and data type float64**
![memory error](https://user-images.githubusercontent.com/73878916/99634445-7c519f00-2a7b-11eb-8606-6ea76d80670b.png)

Hi I am using, the latest PyCaret (2.2.1), I have a dataset with 10,000 and 7000 rows. while using this dataset I am getting a memory error, so is there any way to fix it. I am running the code on server which has 128 Gb ram, and I think memory should be enough to execute the program. Any help will be appreciated 
Thank you in advance

**Comment by angus001** [comment]
I am using this dataset from Kaggle and still having the same issue using Pycaret 2.2.0
https://www.kaggle.com/ntnu-testimon/paysim1

The dataset is 190879 rows and 11 columns. I did sample just make smaller sample.

**Comment by S-UP** [comment]
Same here. DF with shape (48394, 4). Unable to allocate 8.72 GiB for an array with shape (48394, 48394) and data type float32. The very same dataset runs kmeans easily but has issues with pycaret. I've normalized the data myself to check if this is causing it (it is not).

```model_setup = setup(df[['ID', 'Freq']],
#                     normalize = False,
                    silent=True,
                    verbose=True,
#                     experiment_name='Freq'
                   )

```

**Comment by hugomsouto** [comment]
I was having the same issue with some categorical features. Solved passing the category collumns to setup(high_cardinality_features), like this:
```
pyc1 = setup(df, 
             target='DESPESAS_PAGAS', 
             session_id=123, 
             log_experiment=True, 
             experiment_name='analise_custeio_v10', 
             high_cardinality_features=['NO_ORGAO_MAXI_UO', 'NO_ORGAO_UO', 'NO_ORGAO_MAXI_UG', 
                                                        'NO_ORGAO', 'NO_UG', 'NO_NATUREZA_DESPESA_DETA', 'NO_FUNCAO_PT',
                                                        'NO_SUBFUNCAO_PT', 'NO_ACAO_PT'],
             high_cardinality_method='frequency')
```

**Comment by jahidhasanlinix** [comment]
I also have the same issue. When I set my value into 0.09 it works other than when a higher value is set like 1...100 it does not show output and much smaller shows such error, any helps
![screenshot](https://user-images.githubusercontent.com/36171973/144766114-4998f717-ed6b-4ae1-9442-d9c4af9539e9.png)
.

**Comment by goradbj** [comment]
[MemoryError: Unable to allocate 22.8 GiB for an array with shape (3059203866,) and data type int64]() 

I am getting this error when building recommendation system using TFIDF and cosine similarity. Can anyone tell what mistake I am doing? Help appreciated

![1](https://user-images.githubusercontent.com/48828479/155538368-f6e890f4-7503-4e33-bff3-934e649cbdfc.png)
