### ISSUE TITLE
[BUG]: Cant install PyCaret from version 2.3.6 to 2.3.10

### ISSUE THREAD

**Issue by EdgarEAM** [pycaret/pycaret#3451]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [ ] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [ ] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

Cant install PyCaret from version 2.3.6 to 2.3.10 due pip PyCaret tries install sklearn which says is deprecated and recommend use scikit-learn. I have tried install scikit-learn successfully however trying to install again pip PyCaret bring again to the same problem. How can go around this problem?

That problem I didn't find while installing PyCaret 2.3.5
Please, help

![Screenshot_4](https://user-images.githubusercontent.com/128922009/229553065-dcd50f24-bfd0-49f3-a514-741cc0544b21.png)

### Reproducible Example

```python
pip install pycaret==2.3.10
pip install pycaret==2.3.9
pip install pycaret==2.3.8
pip install pycaret==2.3.7
pip install pycaret==2.3.6
```

### Expected Behavior

Successful pip PyCaret installation from mentioned versions

### Actual Results

```python-traceback
Collecting sklearn
  Using cached sklearn-0.0.post1.tar.gz (3.6 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
      rather than 'sklearn' for pip commands.

      Here is how to fix this error in the main use cases:
      - use 'pip install scikit-learn' rather than 'pip install sklearn'
      - replace 'sklearn' by 'scikit-learn' in your pip requirements files
        (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
      - if the 'sklearn' package is used by one of your dependencies,
        it would be great if you take some time to track which package uses
        'sklearn' instead of 'scikit-learn' and report it to their issue tracker
      - as a last resort, set the environment variable
        SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error

      More information is available at
      https://github.com/scikit-learn/sklearn-pypi-package

      If the previous advice does not cover your use case, feel free to report it at
      https://github.com/scikit-learn/sklearn-pypi-package/issues/new
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

### Installed Versions

<details>
'2.3.10'
'2.3.9'
'2.3.8'
'2.3.7'
'2.3.6'
</details>

**Comment by ngupta23** [comment]
This issue is fixed in pycaret version 3.0.0. Can you install this version and check?

**Comment by EdgarEAM** [comment]
Its working, installed 2.3.10
Thank you

**Comment by Shakib-IO** [comment]
Still facing the same issue. Couldn't install 2.3.6 version because of some dependencies.

**Comment by ngupta23** [comment]
Try installing the latest version > 3.0.0 since it comes with a smaller dependency footprint.
