### ISSUE TITLE
Strange behavior when "remove_outliers=True" in classification.setup

### ISSUE THREAD

**Issue by bmberetta** [pycaret/pycaret#810]
When I set "remove_outliers=True" in classification.setup, the transformed train set, and transformed test set, number of columns differs. When I set "remove_outliers=False", the transformed train set, and transformed test set, number of columns match.

With "remove_outliers=False"

X_train = get_config('X_train')
X_test = get_config('X_test')
X_train.shape, X_test.shape

((499, 24), (215, 24))

With "remove_outliers=True"

X_train = get_config('X_train')
X_test = get_config('X_test')
X_train.shape, X_test.shape

((474, 25), (215, 23))

pycaret version:

~$ pip list | grep pycaret
pycaret                           2.2

**Comment by Yard1** [comment]
Would it be possible for you to provide a dataset?

**Comment by bmberetta** [comment]
Not easily I'm afraid. I would have to obfuscate the data.

**Comment by pycaret** [comment]
@bmberetta In that case can you try to reproduce the issue on one of the available datasets on our github? You can access sample data:

```
from pycaret.datasets import get_data
juice = get_data('juice')

# to see list of all datasets available:
get_data('index')
```

**Comment by bmberetta** [comment]
Using the test dataset "juice"

s = setup(
    data=juice,
    target="STORE",
    session_id=42,
    normalize=True,
    normalize_method="robust",
    transformation=True,
    remove_multicollinearity=True,
    remove_perfect_collinearity=True,
    multicollinearity_threshold=0.95,
    remove_outliers=False,
    numeric_imputation="zero",
    data_split_stratify=True,
    silent=True,
)

X_train = get_config('X_train')
X_test = get_config('X_test')
X_train.shape, X_test.shape

((748, 17), (322, 17))

******************************
s = setup(
    data=juice,
    target="STORE",
    session_id=42,
    normalize=True,
    normalize_method="robust",
    transformation=True,
    remove_multicollinearity=True,
    remove_perfect_collinearity=True,
    multicollinearity_threshold=0.95,
    remove_outliers=True,
    numeric_imputation="zero",
    data_split_stratify=True,
    silent=True,
)

X_train = get_config('X_train')
X_test = get_config('X_test')
X_train.shape, X_test.shape

((710, 18), (322, 18))

With the test dataset the number of columns match whether "remove_outliers" is set to True or False.

I have special characters in my column headers, would this cause the issue?

**Comment by pycaret** [comment]
@bmberetta Thanks. the special character might cause an issue. In this case, it would really be helpful if you can somehow anonymize the dataset with actual column names and see if the issue persists and if you can share that here so we can investigate and fix. You can only upload the first 50 rows anonymized with actual col headers. Can you do that?

**Comment by bmberetta** [comment]
I will remove the special characters in the column headers, retest my dataset and report back.

**Comment by pycaret** [comment]
Thanks @bmberetta

**Comment by gm039** [comment]
@bmberetta @pycaret  The mismatch in column size is probably due to the addition of two extra columns (pca & vote_outlier) appended at the end along with the actual X_Train.

**Comment by pycaret** [comment]
@gm039 There shouldn't be new columns introduced in `X_train` due to `remove_outliers`. Do you have any example where we can reproduce this issue?

**Comment by gm039** [comment]
@pycaret I tried it with my case and found these two columns got added. Unfortunately, I can't share my data. I will try to reproduce on public data and share it with you.

**Comment by pycaret** [comment]
@gm039 Are you using pycaret `2.2`. We would really appreciate if you can reproduce the issue and share it here? I can't reproduce this error on `juice` dataset.

**Comment by gm039** [comment]
@pycaret Yes, I am using pycaret 2.2.
Even I am unable to reproduce the issue. It works fine with juice data as both the Transformed Train and Test Set have equal feature size.

**Comment by bmberetta** [comment]
I have confirmed that the issue occurs when any of the column headers include any non-alphabetic character, including a space.

**Comment by bmberetta** [comment]
I have managed to narrow down the issue. It appears to do with the number of numeric and ignored features I have defined. You can reliably reproduce the problem with the Jupyter notebook and data I have uploaded. If you run the notebook as is, you will see that the transformed train and transformed test set columns number differ. If you randomly comment out any one of the numerical or ignored features, and re-run setup, you will see that the transformed train and test set columns match.

[issue-810.zip](https://github.com/pycaret/pycaret/files/5495359/issue-810.zip)

**Comment by Yard1** [comment]
@gm039 @bmberetta I just pushed commit 8856db994d57f38d8b40776677cfcef37979b7d0 that should fix this issue. Could you run
`pip install --upgrade --user git+git://github.com/pycaret/pycaret.git` to install PyCaret's development version and try again?

**Comment by bmberetta** [comment]
@Yard1 I upgraded pycaret per your instructions. Still failing on the test data I sent earlier.

**Comment by Yard1** [comment]
That's odd. I have used the exact same notebook you posted, and it is working as intended for me (column counts are the same and outlier rows are removed from train). I will double check.

**Comment by bmberetta** [comment]
@Yard1 Just to be sure, I'll go through the whole update and test process again as well.

**Comment by Yard1** [comment]
@bmberetta Try `pip uninstall pycaret` before `pip install`, and make sure to restart your notebook so that it reloads the library.

**Comment by bmberetta** [comment]
@Yard1 I can confirm that the issue is resolved. I had a copy of release pycaret-2.2 in a global directory that was overriding my local copy. 

Many thanks for resolving the issue so quickly.
