### ISSUE TITLE
Unable to remove NaNs (missing values) using PyCaret

### ISSUE THREAD

**Issue by WebDevelopmentLabs** [pycaret/pycaret#982]
I am unable to impute NaNs (missing values) with mean and constant using PyCaret. Their documentation says, it does that by default. However, I have tried both (manual and automatic) but nothing is working. I am using my own car sales dataset.

```
clf1 = setup(data = car_data, target = 'Price', numeric_imputation='mean', categorical_imputation='mode', train_size = 0.5)
clf1 = setup(data = car_data, target = 'Price', categorical_features = ['Make', 'Colour'])
```

**Comment by Yard1** [comment]
How can you tell it's not working?

**Comment by WebDevelopmentLabs** [comment]
Well, it still shows NaNs in when I recall the DF. See here please: https://prnt.sc/wj00p9

**Comment by Yard1** [comment]
How are you recalling it? Using `get_config()`?

**Comment by pycaret** [comment]
@WebDevelopmentLabs Models wouldn't even train if there are `null` values in the dataset. Are you able to run `create_model` or `compare_models` successfully?

**Comment by WebDevelopmentLabs** [comment]
> @WebDevelopmentLabs Models wouldn't even train if there are `null` values in the dataset. Are you able to run `create_model` or `compare_models` successfully?

Yes, that is correct. But I did not try that. Let me try and update you in a while.

**Comment by WebDevelopmentLabs** [comment]
> @WebDevelopmentLabs Models wouldn't even train if there are `null` values in the dataset. Are you able to run `create_model` or `compare_models` successfully?

It's not creating the model either.

**Comment by Yard1** [comment]
Is it possible for you to share the dataset and the logs.log file generated automatically in the directory from which you run the script/notebook?

**Comment by pycaret** [comment]
@WebDevelopmentLabs Can you please upload the dataset and Notebook here for us to see what is causing the issue?

**Comment by WebDevelopmentLabs** [comment]
> Is it possible for you to share the dataset and the logs.log file generated automatically in the directory from which you run the script/notebook?

Yes, attached is the dataset file. However, I could not find log file. I am running it on Colab.
[car-sales-extended-missing-data.zip](https://github.com/pycaret/pycaret/files/5855359/car-sales-extended-missing-data.zip)

**Comment by WebDevelopmentLabs** [comment]
> @WebDevelopmentLabs Can you please upload the dataset and Notebook here for us to see what is causing the issue?

Yes, attached is the dataset file. However, I could not find log file. I am running it on Colab.
[car-sales-extended-missing-data.zip](https://github.com/pycaret/pycaret/files/5855363/car-sales-extended-missing-data.zip)

**Comment by Yard1** [comment]
There was an issue that could have been related to what you are facing that was fixed on the development version. Could you install PyCaret with: `pip install -U git+https://github.com/pycaret/pycaret.git` and try again?

**Comment by WebDevelopmentLabs** [comment]
> pip install -U git+https://github.com/pycaret/pycaret.git

Thank you so much for your help. I will try doing that now and update here accordingly.

**Comment by WebDevelopmentLabs** [comment]
> There was an issue that could have been related to what you are facing that was fixed on the development version. Could you install PyCaret with: `pip install -U git+https://github.com/pycaret/pycaret.git` and try again?

It's still the same. I believe it is not creating any models nor comparing them because there the missing values are not imputed. You may have a look over the output in the attached screenshot below:
 
![PyCaret Compare Models](https://user-images.githubusercontent.com/29945777/105832939-58b25400-5fea-11eb-98af-5e9232ff7c56.png)

Also, here is the log file attached herewith for your review. 
[logs (1).log](https://github.com/pycaret/pycaret/files/5872750/logs.1.log)

**Comment by Yard1** [comment]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pycaret/internal/tabular.py", line 2189, in compare_models
    refit=False,
  File "/usr/local/lib/python3.6/dist-packages/pycaret/internal/tabular.py", line 3119, in create_model_supervised
    error_score=0,
  File "/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_validation.py", line 248, in cross_validate
    for train, test in cv.split(X, y, groups))
  File "/usr/local/lib/python3.6/dist-packages/joblib/parallel.py", line 1041, in __call__
    if self.dispatch_one_batch(iterator):
  File "/usr/local/lib/python3.6/dist-packages/joblib/parallel.py", line 831, in dispatch_one_batch
    islice = list(itertools.islice(iterator, big_batch_size))
  File "/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_validation.py", line 243, in <genexpr>
    delayed(_fit_and_score)(
  File "/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py", line 336, in split
    for train, test in super().split(X, y, groups):
  File "/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py", line 80, in split
    for test_index in self._iter_test_masks(X, y, groups):
  File "/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py", line 697, in _iter_test_masks
    test_folds = self._make_test_folds(X, y)
  File "/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py", line 668, in _make_test_folds
    % (self.n_splits))
ValueError: n_splits=10 cannot be greater than the number of members in each class.
```

This would be the issue. Can you try setting `fold` to 5?

**Comment by WebDevelopmentLabs** [comment]
> ```
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/dist-packages/pycaret/internal/tabular.py", line 2189, in compare_models
>     refit=False,
>   File "/usr/local/lib/python3.6/dist-packages/pycaret/internal/tabular.py", line 3119, in create_model_supervised
>     error_score=0,
>   File "/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py", line 72, in inner_f
>     return f(**kwargs)
>   File "/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_validation.py", line 248, in cross_validate
>     for train, test in cv.split(X, y, groups))
>   File "/usr/local/lib/python3.6/dist-packages/joblib/parallel.py", line 1041, in __call__
>     if self.dispatch_one_batch(iterator):
>   File "/usr/local/lib/python3.6/dist-packages/joblib/parallel.py", line 831, in dispatch_one_batch
>     islice = list(itertools.islice(iterator, big_batch_size))
>   File "/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_validation.py", line 243, in <genexpr>
>     delayed(_fit_and_score)(
>   File "/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py", line 336, in split
>     for train, test in super().split(X, y, groups):
>   File "/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py", line 80, in split
>     for test_index in self._iter_test_masks(X, y, groups):
>   File "/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py", line 697, in _iter_test_masks
>     test_folds = self._make_test_folds(X, y)
>   File "/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py", line 668, in _make_test_folds
>     % (self.n_splits))
> ValueError: n_splits=10 cannot be greater than the number of members in each class.
> ```
> 
> This would be the issue. Can you try setting `fold` to 5, or using KFold instead of default StratifiedKFold?

Nopes, it's still the same. You may refer to the attached log file and the screenshot
[logs (2).log](https://github.com/pycaret/pycaret/files/5873547/logs.2.log)
![PyCaret Compare Models 2](https://user-images.githubusercontent.com/29945777/105851133-78ef0c80-6004-11eb-8026-5fcaea848074.png)

**Comment by WebDevelopmentLabs** [comment]
> > ```
> > Traceback (most recent call last):
> >   File "/usr/local/lib/python3.6/dist-packages/pycaret/internal/tabular.py", line 2189, in compare_models
> >     refit=False,
> >   File "/usr/local/lib/python3.6/dist-packages/pycaret/internal/tabular.py", line 3119, in create_model_supervised
> >     error_score=0,
> >   File "/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py", line 72, in inner_f
> >     return f(**kwargs)
> >   File "/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_validation.py", line 248, in cross_validate
> >     for train, test in cv.split(X, y, groups))
> >   File "/usr/local/lib/python3.6/dist-packages/joblib/parallel.py", line 1041, in __call__
> >     if self.dispatch_one_batch(iterator):
> >   File "/usr/local/lib/python3.6/dist-packages/joblib/parallel.py", line 831, in dispatch_one_batch
> >     islice = list(itertools.islice(iterator, big_batch_size))
> >   File "/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_validation.py", line 243, in <genexpr>
> >     delayed(_fit_and_score)(
> >   File "/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py", line 336, in split
> >     for train, test in super().split(X, y, groups):
> >   File "/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py", line 80, in split
> >     for test_index in self._iter_test_masks(X, y, groups):
> >   File "/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py", line 697, in _iter_test_masks
> >     test_folds = self._make_test_folds(X, y)
> >   File "/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py", line 668, in _make_test_folds
> >     % (self.n_splits))
> > ValueError: n_splits=10 cannot be greater than the number of members in each class.
> > ```
> > 
> > 
> > This would be the issue. Can you try setting `fold` to 5, or using KFold instead of default StratifiedKFold?
> 
> Nopes, it's still the same. You may refer to the attached log file and the screenshot
> [logs (2).log](https://github.com/pycaret/pycaret/files/5873547/logs.2.log)
> ![PyCaret Compare Models 2](https://user-images.githubusercontent.com/29945777/105851133-78ef0c80-6004-11eb-8026-5fcaea848074.png)

It worked on 2 folds - idk why. But of course, it eventually gave all the zeros in the results. Attached are the files for your review:
[logs (3).log](https://github.com/pycaret/pycaret/files/5873637/logs.3.log)
![PyCaret Compare Models 3](https://user-images.githubusercontent.com/29945777/105852969-fa479e80-6006-11eb-8f1b-a5a1528bb983.png)

**Comment by Yard1** [comment]
Thanks, I'll run some tests myself when I have a moment.

**Comment by Yard1** [comment]
@WebDevelopmentLabs You are trying to run classification on a regression problem. `Price` is a continuous variable, not a categorical one. Switch to regression module.

**Comment by WebDevelopmentLabs** [comment]
@Yard1 Well, it was a classification problem actuall, where I wanted to predict `Price`, thus set it as `target` :-) the categorical columns were `Make` and `Color`. Could you please check the code below and let me know if I still did something wrong here?

clf1 = setup(data = car_data, target = 'Price', numeric_imputation='mean', categorical_imputation='mode', train_size = 0.5)
clf1 = setup(data = car_data, target = 'Price', categorical_features = ['Make', 'Colour'])

**Comment by Yard1** [comment]
I'm not sure if I understand correctly but it is not possible to treat predicting Price as a classification problem. Classification is used when the target variable is categorical (in other words, when the number of possible values is finite and limited), while the Price column in the dataset is a float with way too many possible values to treat it as a classification problem. You will not be able to run classification on Price and obtain results that will make sense, if at all. You should be instead treating this as a regression problem. Your code is correct and will work, but only if you import from the regression module instead of classification.

**Comment by WebDevelopmentLabs** [comment]
> I'm not sure if I understand correctly but it is not possible to treat predicting Price as a classification problem. Classification is used when the target variable is categorical (in other words, when the number of possible values is finite and limited), while the Price column in the dataset is a float with way too many possible values to treat it as a classification problem. You will not be able to run classification on Price and obtain results that will make sense, if at all. You should be instead treating this as a regression problem. Your code is correct and will work, but only if you import from the regression module instead of classification.

Oops, my bad. Yes, you are right. I was actually having 2 separate colab notebooks with two different datasets each of them. The other one was for classification problem :-) and I accidentally mixed both of them.
